### ISSUE TITLE
Recommended ubuntu prerequisites fail to install

### ISSUE THREAD

**Issue by snoopyjc** [pyenv/pyenv-installer#102]
The recommended ubuntu prerequisites fail to install.  This command:

    sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

fails (Ubuntu 5.8.0-26) because `python-openssl` is not found.

Recommended solution: `s/python-openssl/python3-openssl/`

**Comment by native-api** [comment]
THe instructions at https://github.com/pyenv/pyenv/wiki have been fixed since.
