### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by mgarbade** [pyenv/pyenv-installer#107]
I get the above error when trying to install pyenv on a new machine using

    curl https://pyenv.run | bash

any idea why? 
I could install pyenv successfully on other computers a few months earlier. Maybe it's because github.com changed some bash based authentication settings? (although one should not need login credentials here)

**Comment by robnagler** [comment]
Could you post the error? I'm not seeing anything amiss here.

**Comment by fdfangzhou** [comment]
$ curl https://pyenv.run | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   285  100   285    0     0    283      0  0:00:01  0:00:01 --:--:--   283
Cloning into '/Users/liming/.pyenv'...
remote: Enumerating objects: 751, done.
remote: Counting objects: 100% (751/751), done.
remote: Compressing objects: 100% (505/505), done.
remote: Total 751 (delta 390), reused 345 (delta 151), pack-reused 0
Receiving objects: 100% (751/751), 414.23 KiB | 461.00 KiB/s, done.
Resolving deltas: 100% (390/390), done.
Cloning into '/Users/liming/.pyenv/plugins/pyenv-doctor'...
fatal: unable to access 'https://github.com/pyenv/pyenv-doctor.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
Failed to git clone https://github.com/pyenv/pyenv-doctor.git

**Comment by native-api** [comment]
Not a pyenv-installer problem.

https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/doc/man3/SSL_get_error.pod says that this could happen on an unexpected EOF on the encrypted stream -- i.e. if there are problems with transferring the data.

https://stackoverflow.com/questions/49345357/fatal-unable-to-access-https-github-com-xxx-openssl-ssl-connect-ssl-error/51433565#51433565 indicates that this can happen if you use a proxy and it has problems.
