### ISSUE TITLE
Bug: The virtual environment was not created successfully because ensurepip is not available.

### ISSUE THREAD

**Issue by sabotagebeats** [pyenv/pyenv-installer#125]
```On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv```

**Comment by sabotagebeats** [comment]
fixed with `sudo apt-get install python3.8-venv` this should be added to the prerequesites.

**Comment by Wizard254** [comment]
Recent Ubuntu versions seem to come with a minimal python3 installation, only with basic modules available for system startup. For reference, Ubuntu 21.04 comes with python3.9.

Running the command `$ python3 -m ensurepip` produces the output `/usr/bin/python3: No module named ensurepip`, which confirms that the installed python3.9 does not have the module 'ensurepip' installed.

Installing another python version with `$ sudo apt install python3.10` installs python3.10 with the module 'ensurepip' available.

**Comment by fatbringer** [comment]
i just upgraded to ubuntu 22.04 which comes with python 3.10. The upgrade removed my python 3.9 installation and its virtualenvs. i tried ```sudo apt install python3.10 --reinstall``` since i have the py3.10 installed.

After which i still enocutnered the same error

```
python3 -m venv newpy310
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/user/Desktop/pyenvs/newpy310/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

**Comment by native-api** [comment]
What does this have to do with Pyenv-Installer?
