### ISSUE TITLE
pyenv.run is offline

### ISSUE THREAD

**Issue by balling-dev** [pyenv/pyenv-installer#129]
Hi

The `pyenv.run` website appears to be offline - `curl https://pyenv.run` times out
```bash
curl https://pyenv.run
curl: (28) Failed to connect to pyenv.run port 443: Connection timed out
```
Kind regards,

./ Kristoffer

**Comment by balling-dev** [comment]
Now it is working again! :smiley:

**Comment by robnagler** [comment]
We have been having very serious issues with our colocation facility and their upstream provider. I apologize for the problems. We migrated the site to today to another provider.

**Comment by vkorukanti** [comment]
@robnagler Looks like the website is down again.

**Comment by robnagler** [comment]
Fixed. Sorry about that. Added a site monitor to make sure this doesn't happen again.
