### ISSUE TITLE
How to install a particular release/commit?

### ISSUE THREAD

**Issue by uday-projectn** [pyenv/pyenv-installer#131]
With command :` curl https://pyenv.run | bash` , it will install from master branch latest code everytime.
Is there any option to use a particular commit/release for the installation?

yesterday it worked without any problem in our pipeline.
But today, our pipeline failed because of the python-build tool is expecting this package as prerequisite: (`yum package -y patch`)

So to make it consistent with the repo changes, we want to use a particular commit or relase.

Please suggest.

**Comment by native-api** [comment]
Either install with a Git checkout, or use https://github.com/pyenv/pyenv-installer/blob/master/bin/pyenv-offline-installer which allows you to install from an arbitrary tarball.

For the record, Python-Build has always required `patch`, it just doesn't always use it (only when you install a version for which there are patches provided).

**Comment by native-api** [comment]
That said, there is an outstanding PR: https://github.com/pyenv/pyenv-installer/blob/master/bin/pyenv-offline-installer but it requires some work.
If you're interested, you can implement those changes to help move it along. The best would be to make a PR to that PR (this can be done by specifying the PR branch as base branch when making the PR). As Pyenv maintainer, I should be able to merge that nested PR.

**Comment by native-api** [comment]
That said, there is an outstanding PR: https://github.com/pyenv/pyenv-installer/pull/126 but it requires some work.
If you're interested, you can implement those changes to help move it along. The best would be to make a PR to that PR (this can be done by specifying the PR branch as base branch when making the PR). As Pyenv maintainer, I should be able to merge that nested PR.
