### ISSUE TITLE
/etc/zshenv is sourced twice

### ISSUE THREAD

**Issue by kevinburke** [pyenv/pyenv-installer#14]
On my Mac 10.9 it looks like /etc/zshenv gets sourced twice which causes pyenv to get appended too late in the path.

The execution order for login shells is

/etc/zshenv
.zshenv
.zshrc
/etc/zshenv (again)

So if my pyenv init command is in zshrc, it gets prepended to the path, then /etc/zshenv runs again and sets the initial path to everything in /etc/paths and /etc/paths.d/*.

I'm not sure why it is being sourced twice though it just started happening locally. My zsh version is zsh 5.0.7 (x86_64-apple-darwin13.4.0). I am running pyenv 20141106.

Was wondering if anyone else could comment on this.

**Comment by dkennell** [comment]
Hi @kevinburke , I'm running into the same problem - do you remember what issue was? Thanks!
