### ISSUE TITLE
Safety of remote script execution

### ISSUE THREAD

**Issue by Elijas** [pyenv/pyenv-installer#141]
Hi,

I'd like to ask about the safety of executing remote scripts (curl -> bash). It seems it could pose a major security risk, say if the edge node / DNS were compromised.

It could be argued that this pattern should be discouraged. What are your thoughts about this?

**Comment by native-api** [comment]
https://security.stackexchange.com/questions/213401/is-curl-something-sudo-bash-a-reasonably-safe-installation-method

**Comment by Elijas** [comment]
That explains it, thank you!
