### ISSUE TITLE
-bash: pyenv: command not found

### ISSUE THREAD

**Issue by Sharifah89** [pyenv/pyenv-installer#149]
every time I login to my cluster I get this message -bash: pyenv: command not found even though I am not using it. I have downloaded the tool before but did not manage to run it properly. I want to get rid of this message so I tried to remove as you have in this page but I am still getting the error. How can I make sure that pyenv is completely uninstalled ?

**Comment by native-api** [comment]
You must have some Pyenv-related lines in your shell startup files. Delete them.

**Comment by omaidb** [comment]
# pyenv update
pyenv: no such command `update'

**Comment by omaidb** [comment]
Root cannot install python
