### ISSUE TITLE
pyenv.run Connection Refused, direct link works

### ISSUE THREAD

**Issue by hyperknot** [pyenv/pyenv-installer#152]
I just wanted to report that I repeatedly get Connection Refused for pyenv.run. 

Going into this repo and reading that it's equivalent to:

```
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
```

saved the day, as it works 100% reliably.

I recommend removing that wrapper and using the direct link both here and in the pyenv repo. It saves a few characters but introduces random downtimes.

**Comment by robnagler** [comment]
@hyperknot Thanks for reporting. Do you have a date/time when this occurred? The server is not overloaded, and there are enough connections so it shouldn't be refusing connections.

**Comment by hyperknot** [comment]
Right now. I'm quite sure it's some rate limit or similar, but I only had 2 trials:
- First I tried on a clean Ubuntu and it said that git is required
- So I installed git and re-run the command in like 30 seconds. That 30 seconds seems to have triggered a full IP ban for me.

**Comment by hyperknot** [comment]
No, it was a local virtual machine where I was testing, and I only run the command 2-3 times, not more.
