### ISSUE TITLE
Error: curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 130271 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by rufevean** [pyenv/pyenv-installer#153]
I encountered the following error while trying to use curl to connect to pnevn.run by running 

``` 
curl https://pyenv.run | bash

```

Environment:
    Debian 12 
    curl 7.88.0

**Comment by robnagler** [comment]
This seems to be a temporary error with GitHub. If it is persistent, perhaps there's a network issue.

**Comment by rufevean** [comment]
Its resolved using following steps : 

1)Open the /etc/hosts file using
```
                           sudo nvim /etc/hosts
```
2)Add the following IP address at the end of the file:

                185.199.108.133 raw.githubusercontent.com

**Comment by robnagler** [comment]
That's rather odd. DNS is resolving for me:  https://dnschecker.org/#A/raw.githubusercontent.com

**Comment by rufevean** [comment]
might have something to do with network provider i guess?

**Comment by robnagler** [comment]
Yes, could be a DNS cache server that is wonky. I close for now.
