### ISSUE TITLE
Error: Running Homebrew as root is extremely dangerous and no longer supported. As Homebrew does not drop privileges on installation you would be giving all build scripts full access to your system.

### ISSUE THREAD

**Issue by ccanongo** [pyenv/pyenv-installer#156]
I am on mac os and am trying to run the following line on my terminal 

sudo brew install --yes libssl-dev

 However i then receive this error:

Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

How do I fix this, and am I doing this correctly?

**Comment by joshfriend** [comment]
the command you're trying to run has nothing to do with pyenv or pyenv-installer

**Comment by ccanongo** [comment]
so then how can i correctly install the library I am trying to install?
