### ISSUE TITLE
curl pyenv.run | bash

### ISSUE THREAD

**Issue by robnagler** [pyenv/pyenv-installer#41]
I add bought this domain to simplify the installer line, because I can never remember it :)  You can now install with:

```
curl pyenv.run | bash
```

This redirects to https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer using curl so you don't need `-L` on curl above. 

I don't mind supporting this or if you want, I can turn the domain over to whomever you like.

**Comment by obestwalter** [comment]
@robnagler Wow thanks :) 

@yyuu should control that I guess. I wonder if he has seen it already ...

**Comment by yyuu** [comment]
@robnagler great! I'd like to add reference in READMEs and wiki 😄 

I think I don't need to control the domain for now.... Thanks again!

**Comment by obestwalter** [comment]
o.k. but then I would just like to make a public security announcement here that one should always check the script that hides behind that curl call :)

**Comment by yyuu** [comment]
Even I might be an evil :trollface: Generally speaking everyone should be careful when executing code fetched from remote....

**Comment by robnagler** [comment]
Who judges the judges? :)

One thing we can do to give you more control is create, say, pyenv-run.github.io and point pyenv.run to it.

**Comment by robnagler** [comment]
You should also verify your DNS resolver is right, too. This is probably more serious for most people who are executing code from non TLS connections.

**Comment by obestwalter** [comment]
@yyuu yes that's what I meant :) One should always check the install script before using it.

@robnagler I am not judging anyone - that's for sure, and I think the domain is great. I just have this urge to warn people now and then to not just pipe the whole internet into thier shell, although it is awfully convenient :D

**Comment by robnagler** [comment]
Sorry, I was being obscure. My quote was referring to the philosophical question [Quis custodiet ipsos custodes?](https://en.wikipedia.org/wiki/Quis_custodiet_ipsos_custodes%3F), meaning that there is infinite recursion on validation, and ultimately, you can never know (see 
[Reflections on Trusting Trust](https://www.win.tue.nl/~aeb/linux/hh/thompson/trust.html) by Ken Thompson). Having just read an article on [uXDT](https://www.bleepingcomputer.com/news/security/ultrasound-tracking-could-be-used-to-deanonymize-tor-users/) all is lost, anyway. :(

Be that as it may, I'll keep running it as it. Let me know if you want changes. :)

**Comment by obestwalter** [comment]
I know that as "who controls the controllers" and it's turtles all the way down anyway :D
