### ISSUE TITLE
curl script does not set PYENV_ROOT which conflicts with pyenv/pyenv manual install instructions

### ISSUE THREAD

**Issue by LunarLanding** [pyenv/pyenv-installer#60]
What the title says, also reported in /pyenv as recommended in https://github.com/pyenv/pyenv/issues/1016#issuecomment-337720129

**Comment by ngoldbaum** [comment]
This was very confusing to me trying to get set up on travis, where there is an already-existing pyenv installation that is somewhat out of date. The fix was to unset PYENV_ROOT in my travis setup, but that was very much not obvious.

**Comment by obestwalter** [comment]
Hi @ngoldbaum, thanks for the info. Would you be willing to add the info about that workaround to the README under a heading like "Overriding pyenv installation on Travis"?

**Comment by bmwant** [comment]
On travis
```
  - unset PYENV_ROOT
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - pyenv install 3.5.2
```
did the thing

**Comment by obestwalter** [comment]
Thanks @bmwant integrated this now into the README via https://github.com/pyenv/pyenv-installer/commit/82be0a20cacfd99e5bc38d2177044c562d264a2c
