### ISSUE TITLE
".pyenv is not on master branch"

### ISSUE THREAD

**Issue by joshsleeper** [pyenv/pyenv-installer#66]
A fresh install (with `pyenv-installer` of course) followed by attempting to execute `pyenv update` gives me this set of errors:

![image](https://user-images.githubusercontent.com/849941/37050386-94df7682-2128-11e8-80ce-6ea070463f96.png)

Guessing, but maybe related to this change?
https://github.com/pyenv/pyenv-update/pull/4

**Comment by joshsleeper** [comment]
@joshfriend @yyuu 
any help here?
as far as I can tell, https://github.com/pyenv/pyenv-update is completely broken currently.
i would've filed the issue there, but issues appear to be disabled on that repo.

**Comment by joshfriend** [comment]
maybe because installer does a shallow clone with depth=1? try just [installing pyenv manually](https://github.com/pyenv/pyenv#basic-github-checkout)

**Comment by joshsleeper** [comment]
Sure, that's a viable workaround @joshfriend, and I appreciate you trying to get me up and running.
If the intent isn't to support `pyenv-installer` or `pyenv-update` anymore, that's totally what I'll end up doing.

That said, if you didn't use `pyenv-installer`, I guess I'd say that of course I wouldn't expect you to have these issues.
I'm not claiming that `pyenv` is broken, I'm asserting that `pyenv-installer` and/or `pyenv-update` are broken.

I'm more than happy to try and help with any debugging if I can be given a bit of guidance, but otherwise I guess I'm just reporting that this project isn't currently working properly.

**Comment by joshfriend** [comment]
I've also tried installing from scratch with pyenv-installer, which also worked fine when running `pyenv update`. I find it odd that your output in the first post does not have a message saying `seems you still have not added 'pyenv' to the load path.` That seems to indicate to me that you had it partially set up already?

**Comment by joshsleeper** [comment]
I got the error originally when just running `pyenv update` on a system where it had been working for a few months.
Noticed the error this latest time, did a mostly full uninstall (I'll explain in a sec) and tried reinstalling from scratch.
Same errors.

# "mostly full uninstall"

I explicitly _didn't_ follow these instructions (found [here](https://github.com/pyenv/pyenv-installer/blob/master/README.rst)) and remove these lines from my `.bashrc`, mainly because I reasonably assumed that, since they were manually added to `.bashrc` anyway and it was something I'd need to redo as soon as I removed it, they wouldn't/shouldn't affect a fresh install.

---
and remove these three lines from ``.bashrc``:

.. code:: bash

    export PATH="~/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
---

I did follow all other instructions, including `rm -rf ~/.pyenv` which I double-checked worked before I proceeded with the reinstall.

**Comment by yyuu** [comment]
Even if you install pyenv-update via pyenv-installer, it is clear that it's not a problem of pyenv-installer since [the installer is just checking out the master branch of the plugin repository](https://github.com/pyenv/pyenv-installer/blob/641332f255d0db02db6c1fb0218f7b6c497ed19d/bin/pyenv-installer#L42).

I think this is similar issue as https://github.com/pyenv/pyenv-update/pull/4 which the fix has already been merged into master of pyenv-update. Running `git pull` on `pyenv-update` plugin repository manually might help.

**Comment by joshsleeper** [comment]
@yyuu 
With all due respect, I'd hardly call this issue closed just because you took a guess at solving it.

Unfortunately your suggestion doesn't seem to change anything for me, as shown just below.
`pyenv-update` is indeed on the latest commit from master, but running `pyenv update` continues to claim otherwise.

```
[admin@localhost pyenv-update]$ pwd
/home/admin/.pyenv/plugins/pyenv-update
[admin@localhost pyenv-update]$ git fetch --prune
[admin@localhost pyenv-update]$ git pull
Already up-to-date.
[admin@localhost pyenv-update]$ git status
# On branch master
nothing to commit, working directory clean
[admin@localhost pyenv-update]$ pyenv update
Updating /home/admin/.pyenv...
pyenv-update: /home/admin/.pyenv is not on master branch.
Updating /home/admin/.pyenv/plugins/pyenv-doctor...
pyenv-update: /home/admin/.pyenv/plugins/pyenv-doctor is not on master branch.
Updating /home/admin/.pyenv/plugins/pyenv-installer...
pyenv-update: /home/admin/.pyenv/plugins/pyenv-installer is not on master branch.
Updating /home/admin/.pyenv/plugins/pyenv-update...
pyenv-update: /home/admin/.pyenv/plugins/pyenv-update is not on master branch.
Updating /home/admin/.pyenv/plugins/pyenv-virtualenv...
pyenv-update: /home/admin/.pyenv/plugins/pyenv-virtualenv is not on master branch.
Updating /home/admin/.pyenv/plugins/pyenv-which-ext...
pyenv-update: /home/admin/.pyenv/plugins/pyenv-which-ext is not on master branch.
[admin@localhost pyenv-update]$
```

Furthermore, given the following:
1. `pyenv/pyenv-update` has issues disabled
2. assuming that most people using `pyenv-update` got it because they're using `pyenv/pyenv-installer` (exactly as the docs in `pyenv/pyenv` suggest!)

You say:

> ... is clear that it's not a problem of pyenv-installer ...

but since there's no way to file an issue against `pyenv-update` directly it seems like this is currently the only logical place to deal with `pyenv-update` issues.

**Comment by joshfriend** [comment]
It might be that your version of Git is too old, someone just commented on the change in yyuu/pyenv-update#4 that git 1.8.3.1 shows the "Not on master branch" after the change: https://github.com/pyenv/pyenv-update/commit/59eaf3acf9bdcde90d12427fc12664ae3cb89c1f#r28051582

**Comment by obestwalter** [comment]
> this sucks.

I agree. It sucks that google cloud vm uses an old version of git and you can't even update it. Did you complain already with Google?

**Comment by guyarad** [comment]
I see your point @obestwalter. It's gcloud's faults. The VM is just old. But see my comment on [the PR](https://github.com/pyenv/pyenv-update/pull/4#commitcomment-28286234). In short, just use `refs/heads/*` instead of `heads/*` and it'll work for older versions and newer ones.

**Comment by yyuu** [comment]
@guyarad please open PR instead of issue comment so that we can just merge it.

**Comment by guyarad** [comment]
@yyuu [done!](https://github.com/pyenv/pyenv-update/pull/6)
