### ISSUE TITLE
virtualenvwrapper error, how to fix?

### ISSUE THREAD

**Issue by Yoshimaster96** [pyenv/pyenv-installer#71]
Whenever I start up the terminal in Linux Mint 17.3, I get this message:
pyenv: no such command `virtualenvwrapper'

How do I fix this?

Here's a list of commands I ran leading up to it:
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
pyenv update
pip3 install virtualenvwrapper
sudo pip3 install virtualenvwrapper
sudo pip install virtualenvwrapper
sudo pip install --user virtualenvwrapper
sudo pip3 install --user virtualenvwrapper
sudo apt-get install python-pip
sudo pip install virtualenvwrapper
virtualenvwrapper
python virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh
export PATH=/usr/local/bin:$PATH
source /usr/local/bin/virtualenvwrapper.sh
$PATH

Before this all happened, I deleted some folders in /home/jacob3 related to pyenv, since I no longer needed it. They all started with a dot (.), not sure what that means.

**Comment by obestwalter** [comment]
Best would be to start fresh and install everything they way it is documented. Closing this as very likely being solved in one way or the other ...
