### ISSUE TITLE
https://pyenv.run script still references https://github.com/yyuu/pyenv-installer

### ISSUE THREAD

**Issue by rossmacarthur** [pyenv/pyenv-installer#83]
The command

```bash
$ curl https://pyenv.run
```
Returns

```bash
#!/bin/bash
#
# Usage: curl https://pyenv.run | bash
#
# For more info, visit: https://github.com/yyuu/pyenv-installer
#
set -e
curl -s -S -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash -s -- "$@"
```

I know this still works because of GitHub renaming. But would it not be best to point to 

 https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer ?

**Comment by joshfriend** [comment]
see #81

not even a month later and it's already problematic :/

**Comment by obestwalter** [comment]
True. 

@robnagler could you please update the link?

**Comment by robnagler** [comment]
Done.

**Comment by joshfriend** [comment]
Thanks!

**Comment by rossmacarthur** [comment]
Btw the comment is still "https://github.com/yyuu/pyenv-installer"

**Comment by robnagler** [comment]
Comment updated.

**Comment by obestwalter** [comment]
Thanks @robnagler!

**Comment by yyuu** [comment]
Sorry to be late here, and thanks very much for contribution. I've added @robnagler as a maintainer of pyenv-installer and some more. I should have done this more earlier~

**Comment by robnagler** [comment]
Thanks @yyuu. I didn't know about the rename. I probably should have probably followed pyenv before...
