### ISSUE TITLE
Viewing pyenv.run in a web browser shows installer script without formatting

### ISSUE THREAD

**Issue by iwconfig** [pyenv/pyenv-installer#84]
In an act of impulse I opened [https://pyenv.run](https://pyenv.run) in my browser and was greeted with this:

![2019-03-15-080545_1281x55_scrot](https://user-images.githubusercontent.com/10843441/54414659-23ecca80-46fa-11e9-8927-2b2766f7c314.png)

As you can see, the informative text lack of newlines. Again, a teeny tiny bug but I thought I should let you know.

**Comment by joshfriend** [comment]
it has newlines:

```
$ curl https://pyenv.run/
#!/bin/bash
#
# Usage: curl https://pyenv.run | bash
#
# For more info, visit: https://raw.githubusercontent.com/pyenv/pyenv-installer
#
set -e
curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash -s -- "$@"
```

it's just not supposed to be an HTML document.

**Comment by iwconfig** [comment]
Oh, haha. It was that simple. Can't believe I didn't think of that.

Oh well! Case closed.

**Comment by robnagler** [comment]
This is fixed:

```txt
$ curl -s -D - https://pyenv.run|grep Content-Type
Content-Type: text/plain
$ curl -s -D - http://pyenv.run|grep Content-Type
Content-Type: text/plain
```

**Comment by joshfriend** [comment]
Nice! thank you @robnagler
