### ISSUE TITLE
"Can not proceed with installation. Kindly remove .pyenv from home/"

### ISSUE THREAD

**Issue by InexperiencedGit** [pyenv/pyenv-installer#87]
Hi, 

Absolute beginner here. Trying to install pyenv so I can then install Python on my Pixelbook but keep getting the above error. 

Any help much appreciated.

Thanks.

**Comment by an4cr0n** [comment]
You simply have a previous installation already, if you need to reinstall just run this command before the installation command:
`rm -rf ~/.pyenv`

Also after install don't forget to read the output you receive it contains some lines to paste into .bashrc file!

**Comment by lyssabug** [comment]
Hello,
absolute beginner trying to install Python version 3.8.13. I installed Python but it was the latest version. I need 3.8.13 for a course. when I try to install that version it says it is not found.

**Comment by isabessa05** [comment]
> Hello, absolute beginner trying to install Python version 3.8.13. I installed Python but it was the latest version. I need 3.8.13 for a course. When I try to install that version it says it is not found. Can anyone help me by recommending anything. Thank you.

You should try pyenv install 3.8.13 After that, you can try pyenv global 3.8.13, and that should allow you to run the version you want!

**Comment by Musa-lab-web** [comment]
WARNING: Can not proceed with installation. Kindly remove the '/home/hsshshs/.pyenv' directory first.
please how can i solve this problem?
