### ISSUE TITLE
pyenv: command not found

### ISSUE THREAD

**Issue by DaveScream** [pyenv/pyenv-installer#90]
`[root@v40515 ~]# curl https://pyenv.run | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   285  100   285    0     0     42      0  0:00:06  0:00:06 --:--:--    67
Cloning into '/root/.pyenv'...
remote: Enumerating objects: 660, done.
remote: Counting objects: 100% (660/660), done.
remote: Compressing objects: 100% (495/495), done.
remote: Total 660 (delta 329), reused 253 (delta 74), pack-reused 0
Receiving objects: 100% (660/660), 377.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (329/329), done.
Cloning into '/root/.pyenv/plugins/pyenv-doctor'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 1), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Cloning into '/root/.pyenv/plugins/pyenv-installer'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 1), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Cloning into '/root/.pyenv/plugins/pyenv-update'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Cloning into '/root/.pyenv/plugins/pyenv-virtualenv'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 57 (delta 11), reused 21 (delta 0), pack-reused 0
Unpacking objects: 100% (57/57), done.
Cloning into '/root/.pyenv/plugins/pyenv-which-ext'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.

WARNING: seems you still have not added 'pyenv' to the load path.

# Load pyenv automatically by adding
# the following to ~/.bashrc:

export PATH="/root/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
[root@v40515 ~]# exec $SHELL
[root@v40515 ~]# pyenv
bash: pyenv: command not found
[root@v40515 ~]# exec $SHELL
[root@v40515 ~]#
`

**Comment by DaveScream** [comment]
only these commands helped me
$ echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
$ echo 'eval "$(pyenv init -)"' >> ~/.bashrc
$ echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
$ source ~/.bashrc

**Comment by charlesreid1** [comment]
The pyenv installer should automatically add these lines to your `.bashrc`:

```
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

and running `exec $SHELL` should re-read the `~/.bashrc` file. But running `source ~/.bashrc` explicitly wouldn't hurt. If you want to track this down you can try running the pyenv installer and then check your `~/.bashrc` to make sure the pyenv installer is correctly adding those lines to your `~/.bashrc`.

In any case, that's how it's supposed to work.

**Comment by Jason-2020** [comment]
@charlesreid1 installer didn't add those lines in my `~/.bashrc` or `~/.zshrc`. I had to manually copy those lines.

**Comment by yulio94** [comment]
If you're on Linux, install it with package manager, not pip.
This works for me.
