### ISSUE TITLE
-bash: pyenv: command not found

### ISSUE THREAD

**Issue by nickborti** [pyenv/pyenv-installer#96]
I followed the instructions for installing. But after restarting my terminal, and trying to see the pyenv version, it's giving me this error.

**Comment by guy881** [comment]
This is some kind of problem with your environment. Are you using Linux? Make sure you've got those lines in `.bashrc` or `.bash_profile` (check out which one your system is using). You can debug it by loading it manually like `source .bash_profile`.

```
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by sabotagebeats** [comment]
@guy881 that worked, however now when I close my shell I get the error: `The terminal process "bash" terminated with exit code: 1.` and when I open the shell I get the error 
```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

**Comment by sabotagebeats** [comment]
https://github.com/pyenv/pyenv/issues/1906
